name: Docker Image CI

on:
  release:
    type: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag mahyarkarimi/ffmpeg-ms:${{ github.event.release.tag_name }}
          docker push mahyarkarimi/ffmpeg-ms:${{ github.event.release.tag_name }}
